# Style and colors generated for the z0mbi3 theme.

[global]
origin = top-center
offset = (0, 20)

transparency = 0
corner_radius = 6

frame_width = 0
frame_color = "#93cee9"

font = JetBrainsMono NF Medium 9
icon_theme = "Catppuccin-Mocha, Adwaita""

format = "<span size='xx-large' font_desc='Cantarell 9' weight='bold' foreground='#86aaec'>%s</span>\n%b"

[urgency_low]
timeout = 3
background = "#0d0f18"
foreground = "#90ceaa"

[urgency_normal]
timeout = 5
background = "#0d0f18"
foreground = "#a5b6cf"

[urgency_critical]
timeout = 0
background = "#0d0f18"
foreground = "#dd6777"
