# Style and colors generated for the pamela theme.

[global]
origin = top-right
offset = (28, 65)

transparency = 9
corner_radius = 6

frame_width = 0
frame_color = "#8897F4"

font = JetBrainsMono NF Medium 9
icon_theme = "Gruvbox-Plus-Dark, Adwaita""

format = "<span size='xx-large' font_desc='Cantarell 9' weight='bold' foreground='#8897F4'>%s</span>\n%b"

[urgency_low]
timeout = 3
background = "#1D1F28"
foreground = "#5ADECD"

[urgency_normal]
timeout = 5
background = "#1D1F28"
foreground = "#FDFDFD"

[urgency_critical]
timeout = 0
background = "#1D1F28"
foreground = "#F37F97"
