# Style and colors generated for the yael theme.

[global]
origin = bottom-right
offset = (20, 20)

transparency = 0
corner_radius = 6

frame_width = 0
frame_color = "#33b1ff"

font = JetBrainsMono NF Medium 9
icon_theme = "Candy, Adwaita""

format = "<span size='xx-large' font_desc='Cantarell 9' weight='bold' foreground='#33b1ff'>%s</span>\n%b"

[urgency_low]
timeout = 3
background = "#161616"
foreground = "#42be65"

[urgency_normal]
timeout = 5
background = "#161616"
foreground = "#ffffff"

[urgency_critical]
timeout = 0
background = "#161616"
foreground = "#ee5396"
